### ISSUE TITLE
Status endpoint

### ISSUE THREAD

**Issue by JuniorJPDJ** [milesmcc/shynet#103]
Just for healthchecking!
Could also be added to Dockerfile.

**Comment by milesmcc** [comment]
Does `/healthz` fit your needs (e.g., `https://shynet.rmrm.io/healthz`)? Feel free to reopen if not.

**Comment by JuniorJPDJ** [comment]
It does, but could you then add automatic healthcheck to dockerfile?

**Comment by milesmcc** [comment]
Not sure what that would look like—aren't dockerfiles for build time only?

**Comment by JuniorJPDJ** [comment]
Yes but no!
https://docs.docker.com/engine/reference/builder/#healthcheck
Dockerfile also specifies what default to call on runtime in what purpose (eg. CMD/ENTRYPOINT/HEALTHCHECK)

**Comment by JuniorJPDJ** [comment]
Hey, you closed it and didn't reopen but it would be veeery cool to have healthcheck added into dockerfile.
