### ISSUE TITLE
Use openstreetmap instead of Google Maps

### ISSUE THREAD

**Issue by xgaia** [milesmcc/shynet#106]
It will be nice if the Location option could open openstreetmap instead of Google Maps.

It would make shyness even more shy.

A can PR too

**Comment by milesmcc** [comment]
Sure, that works for me. Feel free to open a PR.

**Comment by olikami** [comment]
Happy to contribute to that, my question is if it wouldn't make more sense to have a setting with two placeholders (lat/long) that we use (and that might OSM be default then). There are a lot of different map services (OSM, GMaps, BingMaps and so forth) and they all support input by lat and long in some form or other.

**Comment by milesmcc** [comment]
That's a good approach. Where would we set the placeholder, and where would users be able to change it? Would this be an environment variable thing?

**Comment by olikami** [comment]
For me that's more of an admin thing to do, not a user, so I think it makes sense to have it as an environment variable. Happy to make a PR later this week

**Comment by milesmcc** [comment]
Great, looking forward to it @olikami!

**Comment by CasperVerswijvelt** [comment]
@olikami Have you tried implementing this? If not i'd like to give it a try too

**Comment by olikami** [comment]
sorry no, have been too busy
