### ISSUE TITLE
create the db specified by DB_NAME if it does not exist

### ISSUE THREAD

**Issue by nektro** [milesmcc/shynet#107]
sending `POSTGRES_DB` to postgres only creates a db with that name if no other databases exist. this would allow shynet to run on databases that are running with other apps already.

**Comment by milesmcc** [comment]
Hmm, I'm not sure I understand. In general, creating a database isn't something we want to do; you should probably do that yourself to make sure everything is setup the way you want. I run my Shynet instance on a Postgres database that also houses other apps and it works well.

I'm going to close this for now, but feel free to follow up if I'm misunderstanding.
