### ISSUE TITLE
Progressive Web App

### ISSUE THREAD

**Issue by NoverNobida** [milesmcc/shynet#116]
Will Shynet support PWA (Progressive Web App)? So that it can be installed to home screen as a lite app on mobile devices.

**Comment by CasperVerswijvelt** [comment]
Think this shouldn't be too hard to implement. Add a `manifest.json` file and a service worker that caches a 'offline' page and displays that when offline. Don't think there's alot more to it than that, I could take a look at doing that maybe

**Comment by NoverNobida** [comment]
Thanks for reply. 
It is easy to add a `manifest.json` file. But it is not convenient as I'm using official docker images. I need to edit `shynet_main:/usr/src/shynet/dashboard/templates/base.html` in container everytime.

**Comment by milesmcc** [comment]
To be honest, I’m not sure this is something that Shynet would benefit from having.

The Shynet web interface is not implemented as a single page app—it is very much an “old school” web app in many senses. (Which is only to say that the approach it takes is tried and true!)

Trying to mold it to fit into a PWA is probably more trouble than it’s worth, and comes with complexity and maintenance costs that I’m not sure are justified. Let me know if I’m off base here.

**Comment by CasperVerswijvelt** [comment]
Being an SPA would indeed deliver a more streamlined experience like you would expect from a PWA, but I don't think it's a requirement for it to be useful. Shynet's UI is already pretty mobile friendly which is what matters most in my opinion. Adding a manifest file would allow users to 'install' it and run it a seperate 'instance' other than a browser tab, which is already an improvement for the mobile experience.

> Thanks for reply.
> It is easy to add a `manifest.json` file. But it is not convenient as I'm using official docker images. I need to edit `shynet_main:/usr/src/shynet/dashboard/templates/base.html` in container everytime.

If it would be added trough a PR you wouldn't have to do that :)

**Comment by haaavk** [comment]
I think @milesmcc is right. This functionality doesn't fit the current implementation.
On the other hand I don't see any problem to add a small separated django app with PWA dashboard only.
It will take more time and require more javascript. It can be done with pure js but there are some useful libraries like Alpine.js.
The most important advantage of this solution is separation. It won't increase complexity of existing code. There won't be any problem to remove it in case of maintenance problems.

**Comment by milesmcc** [comment]
@haaavk the problem with that is when it comes time to build new features, both dashboards need to be updated. I've been thinking about a dashboard overhaul recently, and that would just add a lot of maintenance cost. I really think we should prioritize having "one" main dashboard, unless I'm misunderstanding something fundamental here.

**Comment by haaavk** [comment]
I think about second dashboard as a different slim client. It may contain only sessions chart. 
I considered making small android app but here is no API right now. PWA can just cover this case. 
Main dashboard should be a priority.
