### ISSUE TITLE
Predefined date ranges

### ISSUE THREAD

**Issue by haaavk** [milesmcc/shynet#118]
Hi 
I think predefined date ranges may be a useful feature. 
Litepicker has a plugin just for that (https://litepicker.com/docs/plugins/ranges/).
I managed to apply this plugin and it looks like that.
![Shynet - Screenshot 2021-04-17 16:39:53](https://user-images.githubusercontent.com/818385/115117586-a7dfa380-9f9f-11eb-80e0-6704e77a2af9.png)

There are just default ranges now. 
I can add more ranges and open PR with that.

**Comment by CasperVerswijvelt** [comment]
I would also find this useful
