### ISSUE TITLE
Single-command Docker-compose deploy

### ISSUE THREAD

**Issue by Windyo** [milesmcc/shynet#12]
It'd be great to have a way to run shynet from scratch based on a single docker-compose file.
I finished most of the (minor) adaptations that are needed in order to get that running, so I'll PR when I'm done.

For transparency, modifications include:

- exposing current function Arguments as Environement variables (https://github.com/milesmcc/shynet/tree/master/shynet/core/management/commands)
- Adding a check to Webserver.sh to query postgre on startup and check:
	- if the db is running (otherwise exit container)
	- if the database tables exist, otherwise run migrate
	- if the admin user is set, otherwise run createadmin with the env passed as parameter
	- if the hostname is set, otherwise run hostname with with the env passed as parameter
	- if the whitelabel is set, otherwise run whitelabel with the env passed as parameter

the Compose file itself is pretty much ready but I suck at postgre so it' staking me a while to write valid checks in the bash.

**Comment by milesmcc** [comment]
Got it! Thanks for the contribution. I'm looking forward to the PR when it comes!

And just a side note (you're probably doing it this way already): definitely write your DB checks using Python via the Django ORM, and not directly as SQL. That way we can keep complexity centralized.

**Comment by Windyo** [comment]
Yup, I can't actually do the DB checks via the DB anyway because they're called from the shynet container, not the db one, so the psql command doesn't exist :)

That said I suck at Python/Django so it'll take me a bit. Getting the compose file ready was easy, that part is harder for me :(
