### ISSUE TITLE
Hourly data in graph when date range is 1 day

### ISSUE THREAD

**Issue by CasperVerswijvelt** [milesmcc/shynet#127]
I think it would be neat to show a graph with hourly data when a date range of 1 day is selected, like plausible does (see screenshot). This would also make the predefeined date range of 'Today' more useful (from PR #123).

Can do PR for this if you like this idea.

![image](https://user-images.githubusercontent.com/25928551/115957115-ef66b200-a500-11eb-91a8-2e2beb1aa597.png)

**Comment by haaavk** [comment]
It's a cool idea. 
Maybe give the choice to user. 
Last 48 hours is a valid case to group by hours. 
Moreover longer ranges may benefit from monthly groups.
