### ISSUE TITLE
Sessions percents

### ISSUE THREAD

**Issue by haaavk** [milesmcc/shynet#132]
I tried to show percents of session in some stats. I experimented with pie charts a bit but I wasn't happy about results.
Good responsiveness is not easy to achieve with chart. I decided to try simpler solution and just add percents in brackets after count. Right now it looks like that:
![Shynet - Screenshot 2021-04-27 20:57:14](https://user-images.githubusercontent.com/818385/116299776-68cf0080-a79e-11eb-9d6a-af269c2ede5c.png)

What do you think about this?

**Comment by CasperVerswijvelt** [comment]
Nice! Percentages are indeed something I was missing a bit too. I would maybe remove the brackets and seperate it from the main number in another way (e.g using font size or color, spacing, ...) but thats just my personal opinion :p

**Comment by haaavk** [comment]
Two more variants:
- separate column 
![Shynet - Screenshot 2021-04-28 09:13:17](https://user-images.githubusercontent.com/818385/116365815-ed089e80-a805-11eb-906c-4cf5f47e2559.png)
- no brackets and bigger spacing:
![Shynet - Screenshot 2021-04-28 09:20:16](https://user-images.githubusercontent.com/818385/116365932-0b6e9a00-a806-11eb-9143-d03e91274344.png)

I'm not sure about decimal point. Maybe it should be only integer?

**Comment by CasperVerswijvelt** [comment]
I like the second example better, but maybe a little less spacing. I think decimal point is fine

**Comment by milesmcc** [comment]
To be honest I think your original screenshot looks much better. Could we revert to that? Then I can include for the next release!

**Comment by haaavk** [comment]
Ok. I will make PR tomorrow.

**Comment by wvffle** [comment]
This should be closed as well.
