### ISSUE TITLE
Provide an option to disable the pagination

### ISSUE THREAD

**Issue by Kovah** [milesmcc/shynet#133]
In a recent release, a pagination was introduced in the dashboard. As I have many projects a quick glance over the whole status was great, but now I have to click between the pages to get the whole picture.
Therefore, an option to disable the pagination would be appreciated. 🙏

**Comment by haaavk** [comment]
I think the simplest solution would be to load pagination size from settings. 
It will give you an option to set big number for example 100.

**Comment by CasperVerswijvelt** [comment]
I agree, maybe this should be a setting that can be customizable per user?

**Comment by milesmcc** [comment]
Yeah, we could make it customizable! I like that solution. I'm a bit busy at the moment but I'd happily include this in the next release if someone were to make a PR.

**Comment by haaavk** [comment]
I can add this.
Are we talking about customization on user level or instance level?

**Comment by CasperVerswijvelt** [comment]
Easiest would be instance level

**Comment by milesmcc** [comment]
Going to mark this as closed now that #135 is merged. (You can set `DASHBOARD_PAGE_SIZE` to something very large, which will have the same effect as disabling pagination.)

Thanks to everyone involved!

**Comment by Kovah** [comment]
Thank you so much!
