### ISSUE TITLE
Adding hits data to the chart

### ISSUE THREAD

**Issue by haaavk** [milesmcc/shynet#140]
I think it will be nice to see hits data on the chart. 
Here is some example:
![Shynet - chart2 - Screenshot 2021-05-19 14:15:50](https://user-images.githubusercontent.com/818385/118811009-c8f02880-b8ac-11eb-9f0e-3fbeea6daaab.png)

**Comment by milesmcc** [comment]
Yeah, that is super cool. Open a PR? I’ll merge it.

**Comment by wvffle** [comment]
I guess that this should be closed
