### ISSUE TITLE
Allow "silent failure" for non-origin requests

### ISSUE THREAD

**Issue by ianjmacintosh** [milesmcc/shynet#148]
My CI pipeline runs some end-to-end tests on preview environments and checks for console errors before marking a proposed change as OK to merge. Shynet was logging all this, so I started using the "Allowed origins" but now I'm getting a bunch of console errors.

I'm not sure the right way to fix this, but what do you think of a flag allowing a "silent failure"? i.e., don't log the visit but don't throw a 403.

**Comment by milesmcc** [comment]
Hmm, interesting. Your use case absolutely makes sense, though I hesitate to allow silent failures. I worry that people might not realize their script isn't working if we allowed silent failures. (It could make debugging quite a bit harder for some.) Adding it as a config option might also just really increase complexity.

Is it possible to simulate the response for your Shynet domain in your CI pipeline, or omit the Shynet tag? (I realize then it wouldn't be completely end-to-end, though...)

**Comment by ianjmacintosh** [comment]
@milesmcc Yep, I could use an environment variable or something to keep Shynet from loading on preview environments. Alternatively, since I'm using GitHub Actions, I'm wondering if you can think of a way I could have a sort of "test setup" to handle whitelisting `localhost` and ignoring visits from the GitHub Action runner's IP address (the list of all their IP blocks is a little unwieldy now), then having a teardown step afterwards to put things back the way they were. Does Shynet have a good way for doing that sort of thing?

**Comment by milesmcc** [comment]
Perhaps you could edit the `/etc/hosts/` file to manually point your Shynet domain to some other endpoint that you control?

**Comment by ianjmacintosh** [comment]
@milesmcc maybe, but I'm not sure I'd have that level of access in a _GitHub Actions_ situation like my own. it seems like it'd involve granting an unnecessarily risky/high level of privilege. But if Shynet offers a remotely-accessible endpoint to update the list of allowed origins and ignored IP addresses, this use case may be already supported.

My idea for a Lighthouse CI run on GitHub Actions (for example):

#### Action Steps
1. Set up Shynet for tests
  - Add `localhost` to list of allowed origin 
  - Add runner's IP address to list of ignored IPs
2. Run Lighthouse CI tests
3. Teardown Shynet testing set up
  - Remove `localhost` from list of allowed origins
  - Remove runner's IP address from list of ignored IPs

**Comment by ianjmacintosh** [comment]
Does Shynet offer a way to run those calls? Updating the allowed origin list and ignored IPs without going through the Shynet dashboard UI?

**Comment by milesmcc** [comment]
> Does Shynet offer a way to update the allowed origin list and ignored IPs without going through the Shynet dashboard UI?

Not currently, unfortunately. Not sure what the best way to proceed here is. Is there any way to omit the script when running CI? Sorry if you've already eliminated that option — just thought I'd check.

**Comment by ianjmacintosh** [comment]
Oh yeah for sure, my specific app is just a dumb eleventy blog with Nunjucks, so I can very easily wrap the tag in something like below, I was just hoping to handle the problem within the scope of Shynet

```
{% if not process.env.DISABLE_TRACKING %}
    <script defer src="https://shynet.shynet/shynet/shynet.js"></script>
{% endif %}
```

**Comment by milesmcc** [comment]
In that case, suppressing the script is your best option. Unfortunately there’s nothing in Shynet that would support this otherwise. Thanks for raising the issue, though! I hope you find Shynet useful.
