### ISSUE TITLE
Time zone config

### ISSUE THREAD

**Issue by gumbol** [milesmcc/shynet#156]
hey on issue #155 i did configure the timezone (using heroku)
but the app crashes with logs complaining of wrong timezone setting

**Comment by gumbol** [comment]
i think the code is using the server (us based) built in time configs.

**Comment by milesmcc** [comment]
What is the time zone you entered? It must be a valid time zone according to the international tz database: https://en.m.wikipedia.org/wiki/List_of_tz_database_time_zones

**Comment by gumbol** [comment]
Asia/Kuwait

**Comment by gumbol** [comment]
nvm i fixed it. turs out i had a different configuration in my local copy. all good thanks alot
