### ISSUE TITLE
Can a version be made, or install instructions added, for setting up Shynet without Docker?

### ISSUE THREAD

**Issue by JayDelicious** [milesmcc/shynet#161]
I'm very interested in utilizing Shynet, however I have no Docker experience at present, and my hosting provider does not support docker containers. I run several django projects, and would like to set Shynet up directly as just another django site on my server.

I think many people may prefer to set it up without docker, and having it easily available to use without docker and/or a setup guide for setting it up as a django project without docker may be useful.

**Comment by milesmcc** [comment]
Hi! I'm all for the idea of an official guide for deploying Shynet without containerization. If you or anyone else seeing this would like to submit a pull request adding this information to the [guide](GUIDE.md), please go ahead!

I think I saw a post on Reddit recently complaining that Shynet didn't provide non-Docker support, so I also thought I'd take a moment to explain why that's the case. As an open source maintainer, I need to respond to a _lot_ of people asking for help. Each person runs into different issues in different environments, and providing Shynet as a container image means that there's less variance in the types of issues I need to triage. For example, Shynet uses an external GeoIP database that needs to be present on the filesystem. I download, decompress, and embed that image in the filesystem during the build step. As a result, people don't need to fiddle with downloading, updating, and putting that database in the right place themselves.

Ultimately, the reason why Shynet—and many other self-hosted tools—don't prioritize supporting the app in a non-containerized environment is that doing so will create much more work for the containers. Right now, most of the issues I see people facing are networking or database issues. The reason I don't have to troubleshoot filesystem/geoip/update issues is that Shynet is containerized.

It's also worth noting that Shynet **is not Docker specific.** While we use Docker as our build system, you are not required to use Docker (or Docker Compose) to run Shynet. Right now, you can run Shynet using any tool that runs standard Linux containers. (Personally, I don't run Shynet using Docker.) Just thought that was worth putting out there! :)

**Comment by Alumniminium** [comment]
that's alot of text for saying "it works on my system so I ship my system"

**Comment by JuniorJPDJ** [comment]
No, it's a lot of text for saying "I cannot guarantee it will work on your system as all systems are different, so a way to provide a guarantee is to provide fully working env".
Noone wants to maintain software running with 2349743987 of versions of all libraries and OSes.

This is totally good approach as far as supported environment is getting as much maintenance as software itself.

Noone stops you from using it on your system but noone will waste his time on debugging issues specific to it so it's not supported. This time could be spent better. Feel free to do so, but you are at your own.

Quick guide helping with installation but SAYING IT'S NOT SUPPORTED APPROACH would be cool tho.

**Comment by milesmcc** [comment]
Anyone is welcome to add a note about containerization in the README. In the meantime, I'm going to close this issue. Thanks all!
