### ISSUE TITLE
Missing milesmcc/shynet:v0.11.0 on Dockerhub

### ISSUE THREAD

**Issue by nickgashkov** [milesmcc/shynet#170]
Hello @milesmcc, thank you for your great project, I like it a lot!

I was wondering if it's possible to publish the latest `v0.11.0` release onto the Dockerhub with a matching tag?

**Comment by milesmcc** [comment]
Working on this. For some reason the most recent GitHub Action builds are failing; it usually looks like it's due to some kind of connection error when pulling dependencies from PyPI. I'm currently doing some manual builds -- hopefully that will get things going.

**Comment by milesmcc** [comment]
Fixed and pushed. It’s live now. `latest` will soon point to it as well.
