### ISSUE TITLE
Google Analytics declared illegal in the EU — it's time to push 

### ISSUE THREAD

**Issue by antenore** [milesmcc/shynet#197]
I'm sure you are aware of this news, and I'm sure you are already excited.

More important, is this an issue? It's not at all if you are already riding the wave :-), and you can surely close this, sorry for the interruption…

Just to say, this is my microscopic contribution for one of the best GA alternatives around, if not the only one

https://www.reddit.com/r/opensource/comments/s8dzmw/google_analytics_declared_illegal_in_the_eu/

**Comment by milesmcc** [comment]
❤️

**Comment by LorenzoAncora** [comment]
**Only the old versions of Google Analytics installed before 14 October 2020 are illegal in the EU**[^1]. Those versions are nicknamed _Universal Analytics_ and will stop working automatically[^2].

1. This [official page](https://support.google.com/analytics/answer/11583832) explains how to discover if a manual upgrade of Google Analytics is needed;
2. Users can [upgrade to Google Analytics 4 for free](https://support.google.com/analytics/answer/10089681) by simply replacing the existing HTML tag and be GDPR-compliant again;
3. Companies can then [configure the Consent Mode](https://support.google.com/analytics/answer/9976101) to handle consent automatically or implement their own consent banners if needed.

This was just a quick recap to prevent the spread of misinformation.
Regardless of GA, if one has the resources and the competence to self-host, it is always a better choice. 👋🏻 

[^1]:https://infotrust.com/articles/gdpr-and-google-analytics-is-it-really-illegal/
[^2]:https://support.google.com/analytics/answer/11583528
