### ISSUE TITLE
Problem with favicons

### ISSUE THREAD

**Issue by haaavk** [milesmcc/shynet#213]
DuckDuckGo favicon fetcher doesn't work with my websites. It mostly displays generic icon. 
For my projects on gitlab pages it displays favicon from root domain (login.gitlab.io) instead project page (login.gitlab.io/project).
I think an optional field in service model to hardcode favicon url may be a good idea. 
I believe it's even possible to automatically get favicon url from website url with javascript. 
I can create PR with this.

**Comment by haaavk** [comment]
Closed due to lack of activity.

**Comment by milesmcc** [comment]
Thanks @haaavk. Ultimately I think this sort of thing is out of scope for the project.
