### ISSUE TITLE
Ability to exclude IP addresses/ranges from being counted

### ISSUE THREAD

**Issue by doenietzomoeilijk** [milesmcc/shynet#22]
I think this is self-explanatory - in some cases it's undesirable to have your office or home location counted in the statistics. I don't know if this hinges on tracking and storing IP addresses; this filtering would happen _before_ the data would make it to the database, but I don't know if the IP address removal is done at the client or at the server.

**Comment by milesmcc** [comment]
Yep, great addition. I'll add it to advanced settings sometime this week or next.

**Comment by milesmcc** [comment]
Implemented in v0.4.0. Thanks @doenietzomoeilijk!
