### ISSUE TITLE
Analytics not showing up

### ISSUE THREAD

**Issue by LickABrick** [milesmcc/shynet#24]
I have succesfully installed Shynet behind a reverse proxy. I have created a new service, added the snippet to my site but I don't see any analytics showing up on the interface.

I do see the snippet being loaded on my site, and I see requests being made every 5000ms (hearthbeat value).

**Comment by doenietzomoeilijk** [comment]
This looks a lot like what was encountered in #11. Could you check if your Celery settings are correct? It could very well be that your settings for Celery should be set to be eager. Take a peek at [the end of the thread](https://github.com/milesmcc/shynet/issues/11#issuecomment-623001992) and see if that solves it.

**Comment by LickABrick** [comment]
> This looks a lot like what was encountered in #11. Could you check if your Celery settings are correct? It could very well be that your settings for Celery should be set to be eager. Take a peek at [the end of the thread](https://github.com/milesmcc/shynet/issues/11#issuecomment-623001992) and see if that solves it.

The Celery settings are commented out, should I uncomment them?

# Redis and queue settings; not necessary for single-instance deployments.
# Don't uncomment these unless you know what you are doing!
# REDIS_CACHE_LOCATION=redis://redis.default.svc.cluster.local/0
# If CELERY_BROKER_URL is set, make sure CELERY_TASK_ALWAYS_EAGER is False and
# that you have a separate queue consumer running somewhere via `celeryworker.s$
# CELERY_TASK_ALWAYS_EAGER=False
# CELERY_BROKER_URL=redis://redis.default.svc.cluster.local/1

**Comment by doenietzomoeilijk** [comment]
Abd you're sure you have the latest docker image?

From my very limited knowledge (I only started using this yesterday) it'd seem to me as if the webinterface triggers a worker as well, but I'm not sure if that's the case.

**Comment by LickABrick** [comment]
> Abd you're sure you have the latest docker image?
> 
> From my very limited knowledge (I only started using this yesterday) it'd seem to me as if the webinterface triggers a worker as well, but I'm not sure if that's the case.

Yup, running 0.3.0

**Comment by doenietzomoeilijk** [comment]
Alright, then I'm officially out of my depth. ;-)

**Comment by milesmcc** [comment]
I'm going to add a "Troubleshooting" section to GUIDE.md that will hopefully help in situations like this. If all your cache settings are correct and `CELERY_TASK_ALWAYS_EAGER` is either unset or set to `True`, then the only other thing I can think of going wrong is that your browser has Do Not Track enabled and Shynet is ignoring those requests. Do you still experience this issue when you disable DNT support for the service?

**Comment by LickABrick** [comment]
@milesmcc 

What cache settings do I need to have set?

**Comment by milesmcc** [comment]
The defaults are fine if you're running Shynet on a single instance, so the best answer I can give without knowing more details about your setup is "either none of them or all of them" (i.e., if you have nothing in your env file that mentions Celery/cache/redis, that's fine).

When the browser sends the POST requests, do they stay pending or do they resolve?

**Comment by milesmcc** [comment]
By the way, I just published a small troubleshooting guide, if that's any help: https://github.com/milesmcc/shynet/blob/master/GUIDE.md#troubleshooting

**Comment by JXGA** [comment]
This is identical to what I saw in #11
If I had two tabs open, one with the site to be tracked + ShyNet, when waiting for the POST request to be filled, ShyNet UI was completely locked up. 

1. If you inspect the webpage, do you see any response to the POST request? 
2. If you double click the OPTION method in the inspector, within `xhr.open(` does it contain the correct domain name? 
3. I set `CELERY_TASK_ALWAYS_EAGER=False`, stopped, removed and restarted the latest container, then completed the same sequence with `True`. This seemed to fix the issue.

**Comment by milesmcc** [comment]
What @JXGA describes is a consequence of what happens when Shynet is trying to process a request but is configured to use an external task queue. It tries looking for the task queue (and waits for it to become available), but it never does—and therefore it hangs. Setting `CELERY_TASK_ALWAYS_EAGER` tells Shynet that there is no external task queue, and to just do everything itself.

Because session ingress also requires caching (in order to link hits across requests), a misconfigured/disconnected cache can also cause this issue.
