### ISSUE TITLE
Possible duplicate sessions

### ISSUE THREAD

**Issue by Windyo** [milesmcc/shynet#25]
Opening an issue I actually won't be able to work on because I don't know most the underlying tech.

I've installed shynet but I see some "weird" hit counts and session counts.
In short inspecting the activity for the sites shows mostly three recordings for each person, with the same IP, most of the same hits but wiht minor differences.

I'm unsure if this is actually people loading the site three times, which I find doubtful in the amount of times I see it, or if t's some conflict in the way that sessions are grouped together.
Example.
![image](https://user-images.githubusercontent.com/17938171/80917913-74d1df00-8d51-11ea-85f1-032b63022b80.png)

**Comment by milesmcc** [comment]
Can you show the session details view for each of those sessions? I’m curious if this is someone’s browser calling the `<noscript>` image fallback.

**Comment by Windyo** [comment]
nope, all of the sessions use the JS tracker.

![image](https://user-images.githubusercontent.com/17938171/80924435-6fd45600-8d78-11ea-9f68-f612b0cda80b.png)
![image](https://user-images.githubusercontent.com/17938171/80924441-7cf14500-8d78-11ea-9993-a4fcbc5e457a.png)

**Comment by milesmcc** [comment]
Alright, I'll take a look at this. I haven't been able to replicate this issue, but will see if anything turns up.

(By the way—@Windyo I edited your comment to remove the screenshots, as I wanted to avoid the potentially private IP information from floating around. Just an FYI in case you were wondering what happened.)

**Comment by Windyo** [comment]
I can reproduce it on my sites - if needed I can create you a shynet user on my instance. I can't give you ssh access though.

**Comment by milesmcc** [comment]
@Windyo by the way, do you have multiple frontend servers running?

I could see this being an issue if there are multiple frontend servers that aren't connected to the same cache backend.

**Comment by Windyo** [comment]
Hmmm.

I do have multiple instances of servers running as everything is dockerized, but only one server per website.
Meaning the wiki's on server, with its own database, and the other websites as well.

**Comment by milesmcc** [comment]
Oh, I know what’s happening. Gunicorn is launching 3 instances of Shynet, which aren’t connected via the same cache. That’s causing the duplication. The fix is easy, fortunately: have Gunicorn launch only one instance. I’ll push an update to fix this shortly.

**Comment by milesmcc** [comment]
Alright, this is fixed in v0.3.2. Please reopen if you find the issue continues.

Thanks for the report! This is a pretty shocking issue to be honest; it's likely that it affects pretty much all default Shynet instances except for my own (because I use an external Redis server). So I would not have seen this if it weren't for your report!
