### ISSUE TITLE
Don't phone home when browser has DNT enabled, and project respects DNT

### ISSUE THREAD

**Issue by milesmcc** [milesmcc/shynet#255]
Would love it if someone submitted a PR for this issue! Otherwise I'll try to get to it soon.

**Comment by haaavk** [comment]
Request with DNT are already ignored at backend so I assume we're talking about JS tracker not sending request at all. 
There is JS api to detect DNT enabled in browser but according to MDN it's deprecated. (https://developer.mozilla.org/en-US/docs/Web/API/navigator/doNotTrack)
I suggest to send empty (or almost empty) page.js script when DNT header is set.

**Comment by milesmcc** [comment]
I think that’s the right approach @haaavk — just send a minimal page. If they have script injections etc I think we should still send that.

**Comment by haaavk** [comment]
It's done. I forgot to add appropriate description so issue need to be closed manually.
