### ISSUE TITLE
Statistics included from local development?

### ISSUE THREAD

**Issue by timptner** [milesmcc/shynet#259]
I'm uncertain if Shynet also includes my site visits and sessions while developing locally. I tried reading the source code but didn't find any exclusions of HTTP_REFERERS or ORIGIN matching `localhost` or `127.0.0.1`.

Do I need to block requests to my Shynet host manually or does Shynet automatically ignore all requests coming from localhost?

**Comment by haaavk** [comment]
By default Shynet don't ignore any requests. 
There is an option to add ignored IP's but You have to do it for every service separately.
I personally exclude Shynet script during development (Simple if statement + DEV env variable)

**Comment by CasperVerswijvelt** [comment]
If you go to `Manage` >  `Advanced`
There is a field `Allowed origins` in which you can set the origins for which you want to record statistics

![image](https://user-images.githubusercontent.com/25928551/220930505-ad504048-d5e2-423e-bb73-a650fcb37387.png)
