### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by sparanoid** [milesmcc/shynet#261]
I have a medium-sized website that receives about 300k sessions and 1.5m pageviews per month. I switched to Shynet two weeks ago, but now I have noticed some performance issues with the chart. You can view the video demo here:

https://user-images.githubusercontent.com/96356/228383470-b59bf0d3-c26f-41eb-9f34-0f4dfdd98f92.mp4

After further investigation, I discovered that the issue may be due to the fact that the page is fully server-side rendered. The larger the website traffic, the more data needs to be loaded on the page. If the period is set to the last 30 days, the entire document initial download will be 1.9MB (after gzip compression):

<img width="559" alt="image" src="https://user-images.githubusercontent.com/96356/228386416-47cf6fe9-a491-4371-997a-d9b4647df173.png">

A possible solution is to provide data through an API and replace the chart library with one that has better performance (like Apache EChart?).

**Comment by leeoniya** [comment]
maybe helpful: https://github.com/leeoniya/uPlot#performance

**Comment by sparanoid** [comment]
> Do charts on home page have the same issues?

Yeah you pointed it out. Charts on the home page are smooth as normal.

I removed the Location panel in the browser inspector, which had 100k nodes. This made the page back to normal. It appears that having too many HTML nodes was causing the issue.

<img width="526" alt="image" src="https://user-images.githubusercontent.com/96356/228518100-006f77fe-912d-461a-b43b-dc9d5787b52e.png">

**Comment by sparanoid** [comment]
A better way to handle large amounts of data is to retrieve it through an API and render it in the viewport dynamatically. But this would require a significant amount of refactoring.

**Comment by milesmcc** [comment]
I think we should show the top `n` for everything, rather than all... perhaps we add pagination somehow as well? That should really speed things up.

**Comment by milesmcc** [comment]
Would someone be able to submit a PR that does this? I'd merge quickly.

**Comment by haaavk** [comment]
There can be a button to open paginated view with all results. Just like with sessions.
I can make PR tomorrow.
