### ISSUE TITLE
Missing Docker image for version 0.13.0

### ISSUE THREAD

**Issue by Kovah** [milesmcc/shynet#274]
Hi, I just wanted to upgrade to the new Shynet version which was released a couple of days ago. On the Docker Hub, this version is missing. The only tag that was updated it the `edge` one, but `latest` is still the version from 2 years ago.
I am not sure what the `edge` version is, but I am afraid to change my production environment to it without any information.

**Comment by djerfy** [comment]
Hi @Kovah, yeah unavailable due to error during build, see https://github.com/milesmcc/shynet/actions/runs/5577941089

**Comment by milesmcc** [comment]
Talking a closer look. The build runs correctly locally.

**Comment by milesmcc** [comment]
User error on my part :)

New image should be live shortly. @djerfy, thank you for your help.

**Comment by milesmcc** [comment]
Please feel free to reopen this issue if the image does not publish correctly.

**Comment by Kovah** [comment]
Awesome! Thanks @djerfy and @milesmcc !!! ❤️
