### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by Aesistril** [milesmcc/shynet#275]
How can I reset my password? The reset password button doesn't work because I didn't setup an SMTP server. I have full access to the server running shynet

**Comment by haaavk** [comment]
1. Open bash inside docker image (`docker exec -it CONTAINER_ID bash`)
2. Open django interactive shell (`python manage.py shell`)
3. Import user model (`from core.models import User`)
4. Select user (`u = User.objects.filter(email='USER_EMAIL').first()`)
5. Change password (`u.set_password('NEW_PASSWORD')`)
6. Save changes (`u.save()`)

**Comment by milesmcc** [comment]
Thanks @haaavk!
