### ISSUE TITLE
Fastest way to deploy shynet

### ISSUE THREAD

**Issue by thomasgroch** [milesmcc/shynet#28]
This is a really great project, the [simple image tracker script](https://github.com/milesmcc/shynet/blob/master/shynet/analytics/templates/analytics/scripts/page.js) looks awesome. I will run it for my personal websites.
I was wondering if [Shynet could be deployed as a Dockerized Heroku App](https://blog.heroku.com/six-strategies-deploy-to-heroku#deploying-with-docker)? And if so, could be possible to create a quick deploy button?

So I did It. And I think it is working pretty well.

## Deploy Shynet on Heroku

You may try it in your account right now. Just go to my [shynet fork](https://github.com/thomasgroch/shynet/blob/master/GUIDE.md#quick-deploy) and press the "Deploy to Heroku" button.

After deploy your app it will not work. You need to manually fill the generated database config like so:

```
heroku config:get DATABASE_URL --app=my-app

heroku config:set DB_NAME "myDbName" --app=my-app
heroku config:set DB_USER "myDbUser" --app=my-app
heroku config:set DB_PASSWORD "myDbPassword" --app=my-app
heroku config:set DB_HOST "myDbHost" --app=my-app
heroku config:set DB_PORT "myDbPort" --app=my-app

heroku restart --app my-app
```

## Gmail SMTP (quick'n dirty)

To use your gmail account as smtp you need to:

[Allow less secure apps](https://support.google.com/accounts/answer/6010255?hl=en)
[Display Unlock Captcha](https://accounts.google.com/DisplayUnlockCaptcha)

```
heroku config:set EMAIL_HOST "smtp.gmail.com" --app=my-app
heroku config:set EMAIL_HOST_PASSWORD "mypassword" --app=my-app
heroku config:set EMAIL_HOST_USER "myusername@gmail.com" --app=my-app
heroku config:set EMAIL_PORT "465" --app=my-app

heroku restart --app my-app
```

I think it would also be possible to recognize the presence of heroku's environment variable DATABASE_URL, parse it and then overwrite the others (uppon the application boot).

Does anyone have an interest in making skynet compatible with heroku?

**Comment by lbernick** [comment]
Hi Thomas! I am also trying to get shynet set up on Heroku. Is there currently a way you know of to set the DB credentials required by shynet so they don't have to be manually updated if DATABASE_URL changes?
I also saw that in your fork you modified `webserver.sh` to bind to the port given by the PORT envvar-- wanted to make a note of it for anyone reading this issue as it was the only other problem I encountered when deploying to heroku. I'd prefer to keep using Miles' docker image rather than cloning your fork or maintaining my own clone, so it would be great to see heroku support added.

**Comment by milesmcc** [comment]
Hey! Just wanted to say that the `PORT` environment variable is now used to set the bind port, and that the installation process has been streamlined a bit more (thanks @lbernick for pointing out some of the issues).

**Comment by milesmcc** [comment]
@thomasgroch, feel free to open a PR with your changes. In the meantime, I'm going to close this issue.

**Comment by gschurck** [comment]
Also a Dokku plugin could be really cool for self-hosting on VPS.

**Comment by Keromyru** [comment]
I am curious if anyone has deployed via Dokku before? Since it has the ability to deploy several different ways would be very cool to see.

**Comment by gschurck** [comment]
Btw, [Caprover](https://github.com/caprover/caprover) and [Coolify](https://github.com/coollabsio/coolify) are also interesting self-hosting alternatives to consider.
