### ISSUE TITLE
Don't commit MaxMind license key to your repository

### ISSUE THREAD

**Issue by ugexe** [milesmcc/shynet#292]
https://github.com/milesmcc/shynet/blob/45fafc35070416bbc9df420e2df6593f43efd4dd/Dockerfile#L18

**Comment by milesmcc** [comment]
This is intentional; we want anyone to be able to create a build. It's functionally only an access code. I'm comfortable with it being public.

**Comment by ugexe** [comment]
Typically one would allow users to provide their own maxmind license key, as distributing the license key itself is probably against the ToS or licensing agreement. If the key were to be deactivated because of this, then this software would be broken for users and they would have no way to work around it.

**Comment by milesmcc** [comment]
Thanks! That said, I'd really like everything to "just work" out of the box without users having to create MaxMind API keys.

**Comment by milesmcc** [comment]
(I also recognize that you work at MaxMind; perhaps we can work out some kind of licensing system that allows us to distribute the MMDB with our package? IIRC the API key gating is to comply with GDPR requirements.)
