### ISSUE TITLE
502 Bad Gateway 

### ISSUE THREAD

**Issue by webmastermario** [milesmcc/shynet#295]
Hello,

i try to install via docker-compose but i receive this error when accesing it via the IP:PORT http://18.170.91.114:8080/ 

my nginx.conf file:
server {
    server_name 18.170.91.114;
    access_log /var/log/nginx/bin.access.log;
    error_log /var/log/nginx/bin.error.log error;

    location / {
        proxy_pass http://18.170.91.114:8080;
        proxy_redirect off;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Url-Scheme $scheme;
    }
    listen 80;

}
.env is unchanged. i just copied TEMPLATE.env to .env 
and docker-compose.yml is also unchange with 
8080:80 port.

What can i do to correct this?

**Comment by webmastermario** [comment]
when i make         proxy_pass http://shynet_main:8080; i receive 400 Bad Request

**Comment by haaavk** [comment]
It looks ok via http://18.170.91.114/.
Is there a reason to use PORT?
