### ISSUE TITLE
Question regarding Requests

### ISSUE THREAD

**Issue by webmastermario** [milesmcc/shynet#297]
Hello,

i have a question regarding the script which i put on the website. Why does it request the script.js every few seconds when
checking inside my console? Is that normal?

Thanks

**Comment by CasperVerswijvelt** [comment]
It only requests the script once using a `GET` request, the following calls are `POST` requests (to the same URL) but those responses only contain a small json result: ```{"status": "OK"}```

![image](https://github.com/milesmcc/shynet/assets/25928551/f9345458-241f-4322-93b2-ced95d4caba6)
