### ISSUE TITLE
Disable all email features option

### ISSUE THREAD

**Issue by jpds** [milesmcc/shynet#30]
I have an instance of Shynet deployed on a Kubernetes cluster. After I created my super user account - I tried to log in with the credentials and was told that I needed to verify my email.

However this instance has no email servers available and never will, it would be useful if there was a single option I could set to disable all email services.

**Comment by milesmcc** [comment]
Yes, it would be useful to be able to remove the email verification process.

Did the email verification prompt print to the console, though? Were you able to get into your account?

**Comment by jpds** [comment]
> Did the email verification prompt print to the console, though?

I didn't check that at the time and it seems that my container has redeployed onto another host (lost the logs).

> Were you able to get into your account?

Only by manually logging into the admin interface and marking my user account as verified. :-)
