### ISSUE TITLE
Health check endpoint

### ISSUE THREAD

**Issue by jpds** [milesmcc/shynet#31]
It would great if there was a `/healthz` endpoint that "pinged" the database (usually done with a "SELECT 1") on the SQL DB and returns a 200 OK on successful DB connection.

Kubernetes would leverage this to know which shynet pods to remove from serving user traffic as they couldn't get to the database anyway.

- https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

**Comment by milesmcc** [comment]
This is a good addition; I've added it to the roadmap.

**Comment by mrspartak** [comment]
@milesmcc need more info about /healthz page. Now it is an HTML page with statuses of cache and DB services. How PING or Docker/K8s services could know if something is not ok?

**Comment by milesmcc** [comment]
@mrspartak As far as I'm aware, if it returns an HTTP 200, it's OK -- otherwise it's not. All the HTML is just for diagnostics.

**Comment by mrspartak** [comment]
Yes, just found info at https://pypi.org/project/django-health-check/
HTTP Status code will be 500 if something isn't right. Also, it is possible to JSON output passing /healthz/?format=json
