### ISSUE TITLE
Add import from Matomo and GA ?

### ISSUE THREAD

**Issue by McFlyPartages** [milesmcc/shynet#323]
Hello,

I came across this project completely by chance, but it seems to be what I'm looking for. I currently use Matomo, but the interface and functions are far too cumbersome for my use.

Switching to Shynet seems obvious, but is it possible to import my Matomo data to keep track of my statistics?

Perhaps an interesting feature?

I'm also thinking of GA, even though I don't use it.

Thank you for this wonderful and respectful tool.

McFly, Anthony

**Comment by milesmcc** [comment]
Thanks for the feature suggestion! It's always helpful to know what people are interested in. Unfortunately I think this is outside the scope of the project.

**Comment by McFlyPartages** [comment]
It's a pity, because I don't think some people want to lose their history.

Thank you for your reply and your project.
