### ISSUE TITLE
Tracking Code uses http which results in blocked POST requests on https pages

### ISSUE THREAD

**Issue by patrickuhlmann** [milesmcc/shynet#334]
The tracking code (displayed in shynet) is always using the http protocol. Even if the page is setup using https. It is possible to adapt the tracking code to https and this will also succeed in tracking the initial request but then subsequent POST requests are triggered (probably to find out the visit duration). These are done using http. Which are blocked in both Firefox and Chrome if the main page is using https.

This behavior can be observed for example here: https://uhlme.ch/

Is it possible to implement any solution like:
- Ability to choose https or http in shynet in the settings for every service or even just extract it from the link (if specified)
- Using the same protocol for subsequent POST requests as was used for the initial loading of the script or just in general the same protocol that is being used by the site

**Comment by patrickuhlmann** [comment]
I see that it seems to work for https://polititweet.org/. Wondering if the problem is with the traefik setup. In any case shynet is called on https but uses an http url in the tracking script that is being returned

**Comment by patrickuhlmann** [comment]
Ok it was my mistake. I set the property SCRIPT_USE_HTTPS which controls if it is https or http to True in the compose.yaml file but I should have set it to 'True' because Django expects it as a string not as a boolean.

**Comment by Jason-JP-Yang** [comment]
I also faced this problem, can you give a more detailed solution please. What do you mean set compose,yaml:SCRIPT_USE_HTTPS = 'True', I use docker run to deploy shynet and do not have this file.....

**Comment by patrickuhlmann** [comment]
> I also faced this problem, can you give a more detailed solution please. What do you mean set compose,yaml:SCRIPT_USE_HTTPS = 'True', I use docker run to deploy shynet and do not have this file.....

SCRIPT_USE_HTTPS is an environment variable. You can set it also with the parameter -e when running with docker
