### ISSUE TITLE
DB Configuration for Heroku deployment

### ISSUE THREAD

**Issue by lbernick** [milesmcc/shynet#36]
Currently, DB configuration for shynet uses the envvars DB_HOST, DB_USER, etc. Deployments to Heroku require your app to accept the environment variable DATABASE_URL, the value of which can change at any time. Currently, I can manually set the environment variables accepted by shynet based on the value of DATABASE_URL, but I will have to update the variables whenever the value of DATABASE_URL changes. 

I would like the envvar DATABASE_URL to be supported in addition to the current database configuration options. I know it's less than ideal to have two means of configuring the same property, and not everyone may share this use case, so I'd like to hear what other users and contributors think. Happy to make a PR with these changes.

**Comment by milesmcc** [comment]
I’m leaning toward adding this. As long as the duplication of env variables is well documented, this shouldn’t present too much of an issue. Plus, it’s really only necessary for the Heroku users, so we won’t need to include DATABASE_URL as a default in `TEMPLATE.env`.

Note: PR #38, once merged, will implement this.

**Comment by milesmcc** [comment]
All set! This was implemented in #38. Thanks @lbernick.
