### ISSUE TITLE
Data not showing up

### ISSUE THREAD

**Issue by mannp** [milesmcc/shynet#41]
Hi there, I am in a similar position to https://github.com/milesmcc/shynet/issues/24 but have tried the suggestions from there and cannot get data to be logged.

I have also tried the troubleshooting ...

I am using an nginx reverse proxy and can access the admin area of shynet.

What is weird is that if I go to the script created by shynet for my site and paste in into a browser, I get a 404, which is odd!

It uses an 'ingress' directory which isn't present on my server, so am not sure if shynet should be redirecting that in some way....as I am not using Kubernetes.

Thanks for any help.

Cheers

**Comment by milesmcc** [comment]
Can you paste 1) the script that Shynet generates, and 2) a redacted version of your environment file?

**Comment by mannp** [comment]
Okay, apologies for the noise, as I should have read everything...

I took this to mean the hostname of the monitored site rather than that of the shynet instance....that is why the scripts were pointing to my website and not the shynet instance...its obvious now I think about it but not at the time :)

I am up and running, thanks for creating and hope you keep improving :)
