### ISSUE TITLE
automatically ignore IP of shynet user/admin

### ISSUE THREAD

**Issue by fightforlife** [milesmcc/shynet#43]
I am just trying shynet on some small personal websites.
Since there is not much traffic in these site, I create most of it when working on content or writing new posts. That kind of distorts the overview.

Would it be possible to add a toggle to the advanced settings of a service to exclude the IP-address of the shynet user for eg. 24h. Most ISPs change the IP-adresses once a day.

possible workarounds right now:
I could add every IP adress I get from my ISP to the ignore list, but this is a lot of work. 
I also could ignore a broader range of IP-adresses  like 127.0.0.1/32, but this would possibly block other users and/or sometimes it wont match my real IP.

So I think the best option would be to check the shynet users IP-adress and exclude it for the day.
Another possibility would be to check a ddns Domain A-record for the current IP-adress.

What do you think?
Best regards!

**Comment by milesmcc** [comment]
Hmm, unfortunately I don’t think this is something that fits in Shynet. You can always ignore your own IP—my home IP changes once every six months or so—and keeping track of admins’ IPs adds a lot of complexity. (Note that this is made even more complex by the fact that there are arbitrarily many users that can be associated with any service on Shynet.)

Thanks for the idea—I really appreciate it when people share ideas for Shynet. Unfortunately, I just don’t think this one is something that we can implement.
