### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by yasoob** [milesmcc/shynet#44]
There is a lot of room for improvement in the UI. I am going to list some ideas here.

- ### Merge referrals from the same domain in a drop down

I am thinking about something like what Wordpress.com does. They put all popular search engines under one list item and put all different referral paths from one domain under one list item. This is useful to get more information at one glance.

In addition to this, I am not sure why Shynet is forcing me to vertically scroll all the different tables. It clearly crops the URL to make space for the actual count right next to it. For some reason it is spacing the count more than it should and it is causing an overflow.

![Wordpress Referral UI](https://imgur.com/l5bYeYu.png)

- ### Auto refresh the `online` user count

This is self explanatory. Right now I manually refresh the page to see new value. Unless I am missing something we don't have this feature. Instead of enabling this by default we can enable this on a per-site basis. Adding this as a toggle setting will make sure we don't force the server do extra work when it isn't really required by the user.

- ### Add icons behind country names

Again, wordpress does this beautifully. There is a finite list of countries and I am sure we can get a free list from somewhere. The cacheability and the size of these icons will make sure the server doesn't work over-time.

The same feature request goes for device types.

![Wordpress country icons](https://imgur.com/PXHZVy7.png)

- ### Add a favicon to the shynet instance

This one is fairly simple but low priority. Right now there is no favicon and it doesn't let Shynet stand out from the crowd of tabs I usually have open. A favicon will make it easy to spot which tab is Shynet when the number of open tabs get large enough.

![image](https://user-images.githubusercontent.com/3696393/83985913-e846ad80-a908-11ea-9278-ba638ac797d3.png)

- ### Reduce UI friction

Currently, whenever a user creates a new service the dashboard for that service is show as the next step. I would love Shynet to show the dashboard but also open up a popup with the installation snipped. We know that the next logical step for any user is going to be to copy the snippet so let's make it easier for them to do that :)

**Comment by milesmcc** [comment]
Thanks for writing this out. The lack of country icons seems like it's a bug with your browser, though -- Shynet simply uses the flag emojis. (Does [this page](https://flagpedia.net/emoji) also not show flags?)

Because the UI is functional as-is, I'm not going to implement these changes immediately, but I'd like to at least think about implementing for v1.0. In the meantime, feel free to submit a PR!

**Comment by yasoob** [comment]
Interesting... Edge and Firefox aren't rendering flag emojis for me. I am running Windows 10 and I assume this has to do something with my windows. My mobile browser is rendering them perfectly. Thanks for pointing this out! This is what I get on my laptop:

![image](https://user-images.githubusercontent.com/3696393/83992710-3070ca80-a91f-11ea-87fe-149defe4ca61.png)

And yeah I will definitely look into contributing some code once I get some free time on my hands. I was already thinking about doing that! :)

**Comment by milesmcc** [comment]
That’s pretty neat, I think that’s definitely worth incorporating. That said, I’m a bit weary of linking to third-party resources, DDG or otherwise.

**Comment by CasperVerswijvelt** [comment]
About the flag emojis: Windows font just doesn't support them for some reason. Maybe the emoji flags should be replaced by svg's from this repository? https://github.com/hampusborgos/country-flags

**Comment by CasperVerswijvelt** [comment]
Maybe a good solution for the `Reduce UI friction` point, is to show the script snippet at the top of the service page when there are no recorded hits yet. When a single hit/session has been recorded I think it's safe to assume that the user has setup the snippet in his/her site correctly, and then we can hide the snippet.

**Comment by milesmcc** [comment]
Closing this for now, but I hope that we use this to inspire future changes.
