### ISSUE TITLE
Googlebot is generating hits

### ISSUE THREAD

**Issue by rubenvanerk** [milesmcc/shynet#45]
![image](https://user-images.githubusercontent.com/20305359/84417678-48de2f00-ac16-11ea-9242-200d4711466a.png)
Is there an option to filter out bots or is something wrong with my configuration?
Anyway, thanks for this project. Looking promising so far!

**Comment by milesmcc** [comment]
Googlebot hits are recoded, but they don’t affect your overall stats (sessions, pageviews, etc). Or at least they _shouldn’t_. If you’re looking for a more drastic approach that even excludes Googlebot from the session list, you could add Google’s crawler IP range to your Ignored IPs.

Hope this helps.

**Comment by rubenvanerk** [comment]
That's weird because Googlebot hits are definitely affecting my overall stats. 

Device types section: 
![image](https://user-images.githubusercontent.com/20305359/84420854-f5baab00-ac1a-11ea-8bca-bcacf5a92d01.png)
Totals:
![image](https://user-images.githubusercontent.com/20305359/84420892-05d28a80-ac1b-11ea-9e09-a87229918497.png)
I took a quick look and I expected the hits to be filtered out on the line below, but I can't find anything that filters out the `device_type` of `ROBOT`.

**Comment by milesmcc** [comment]
You're right--I'm mixing this up with another change I made. A few weeks ago I made a commit that removed crawlers from showing up as mobile devices (because sometimes Googlebot will try to request the mobile site, sometimes tricking the device type field), and got that mixed up with an overall exclude.

Eventually, I'd like to implement much more advanced filtering (i.e., by far more than just date), and bots will certainly be a filter option.

**Comment by rubenvanerk** [comment]
What you're describing is also happening in my case: 
![image](https://user-images.githubusercontent.com/20305359/84432667-6f5b9480-ac2d-11ea-830e-4fe851cc99aa.png)
![image](https://user-images.githubusercontent.com/20305359/84432849-b053a900-ac2d-11ea-8cab-63befc86f1f8.png)
I have 44 real sessions in the past ~24 hours

**Comment by rubenvanerk** [comment]
[Google themselves discourage to ignore IPs](https://support.google.com/webmasters/answer/80553?hl=en)

For now, I just regularly delete robot sessions through the admin.

**Comment by milesmcc** [comment]
Maybe the best thing to do is an an option to ignore all bots? Then they won’t ever be logged in the database, thus saving you space.
