### ISSUE TITLE
Possible to add to Dockerhub?

### ISSUE THREAD

**Issue by JoshuaMunoz** [milesmcc/shynet#46]
I dunno if that's a thing or not - I see it can be run in a Docker container.

**Comment by milesmcc** [comment]
Hey! Not entirely sure what Dockerhub is, but if it's hub.docker.com, Shynet is available on it and namespaced as `milesmcc/shynet`.

I'm going to close this issue for now, but feel free to reopen if I'm misinterpreting the issue.
