### ISSUE TITLE
Dockerfile build hangs when downloading geoip

### ISSUE THREAD

**Issue by abulte** [milesmcc/shynet#49]
Hi,

I'm trying to build the docker image but the step `curl "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-ASN&license_key=G4Lm0C60yJsnkdPi&suffix=tar.gz"` hangs (w/o a timeout, at least not for 30 minutes). Downloading this file locally won't work either.

This probably does not depend directly on you, but I'd still like to be able to build the image ;-)

Any help appreciated!

**Comment by milesmcc** [comment]
Ugh. I guess MaxMind changed their API key system. I'll update the Dockerfile...

**Comment by milesmcc** [comment]
...or maybe they shut down the key that we were using. I'll update it with another one. MaxMind, I really wish you offered a way to download these without keys.
