### ISSUE TITLE
"Allowed hostnames" field only allows one hostname

### ISSUE THREAD

**Issue by odensc** [milesmcc/shynet#52]
![image](https://user-images.githubusercontent.com/1520776/85250197-bbb38b00-b40a-11ea-8764-6786aa0350a3.png)

The `Access-Control-Allow-Origin` header is [simply set to the value of this field](https://github.com/milesmcc/shynet/blob/6978bbd03e68525f50ecf35ffc84126e4007bef8/shynet/analytics/views/ingress.py#L52), meaning you can't allow multiple origins for one service (e.g. `https://example.com,https://www.example.com`), as `Access-Control-Allow-Origin` only allows you to specify one origin.

The server needs to check if the request `Origin` header matches any hostname in this field, and send the corresponding origin back to the browser as `Access-Control-Allow-Origin`.

**Comment by milesmcc** [comment]
Yeah, good catch. This is challenging. I'm hesitant about doing some kind of server-side parsing of hostnames, but it seems like the only option.

**Comment by milesmcc** [comment]
Alternatively, we can set the `Access-Control-Allow-Origin` header to be always be `*` and do hostname filtering during the ingress step. The client just won't know its requests are being sent into a black hole. That feels like a regression from a visibility/debugging standpoint, but also feels a bit less hacky than dynamically parsing the requested host and responding accordingly.

**Comment by odensc** [comment]
You don't really need to do any parsing - it's a simple check if the origin is in the list of allowed origins. Psuedo code: 

```python
if request.headers["Origin"] in allowed_origins:
  response.headers["Access-Control-Allow-Origin"] = request.headers["Origin"]
```

See the spec: https://fetch.spec.whatwg.org/#http-access-control-allow-origin

The Access-Control-Allow-Origin header is strict enough that it's just a string equality check.

**Comment by milesmcc** [comment]
Right, it's not too complicated -- my concern is more to do with whether it's the right thing to do from an overall design standpoint. I think the approach you've explained is the right one though.
