### ISSUE TITLE
Public sign-ups are not allowed at this time. on signup page

### ISSUE THREAD

**Issue by anands9288907423** [milesmcc/shynet#53]
I am deployed Shynet on heroku.
it will opens login page and i don't have a registred account.
i am opened signup tab and it will shows 
"Public sign-ups are not allowed at this time."
How to create an account ?

**Comment by milesmcc** [comment]
Hey! Please refer to the [Heroku section of the Getting Started Guide](https://github.com/milesmcc/shynet/blob/master/GUIDE.md#heroku). Specifically, to create an account, you'll need to follow the commands listed below the deploy button.

You'll need to run `heroku run --app=<your app> ./manage.py registeradmin <your email>` and `heroku run --app=<your app> ./manage.py hostname<your hostname>`. See the guide for more info.

**Comment by Luca-Castelnuovo** [comment]
Most of your questions can be answered if you look at https://github.com/milesmcc/shynet/blob/master/GUIDE.md#installation

To create an admin account use the following snippet.
> Create an admin user by running docker run --env-file=<your env file> milesmcc/shynet:latest ./manage.py registeradmin <your email>. A temporary password will be printed to the console.

To allow normal accounts to be created publicly
> Set `ACCOUNT_SIGNUPS_ENABLED=False` in your .env to `ACCOUNT_SIGNUPS_ENABLED=True`

And if you want to manually create accounts
1. login to your admin account
2. navigate to https://yourshynetinstance.com/admin
3. click on `users` 
4. click on `create`

**Comment by anands9288907423** [comment]
I am followed Getting started Guide https://github.com/milesmcc/shynet/blob/master/GUIDE.md#installation
and it works
