### ISSUE TITLE
Expose "sendUpdate" function for external use.

### ISSUE THREAD

**Issue by odensc** [milesmcc/shynet#54]
It'd be nice if the `sendUpdate` function in `script.js` was exposed. In SPAs, Shynet doesn't properly detect page transitions because the browser page is never reloaded. Hence you have to wait for the next heartbeat for anything to be tracked.

If the `sendUpdate` function was exposed, it could be called in your router transition event handler and would allow for these events to be tracked. For example with Fathom and Next.js you can do something like this:

```js
Router.events.on("routeChangeComplete", () => {
  fathom.trackPageview();
});
```

**Comment by odensc** [comment]
The JS script could probably use some other updates too, like using `window.addEventListener` instead of directly overriding the `onload` prop. Let me know if you're open to these changes, I'm glad to make a PR.

**Comment by milesmcc** [comment]
Yeah, I'd like to do a pretty significant refactoring of the script -- I'll definitely expose some kind of `shynet.newHit()` function.

**Comment by odensc** [comment]
Latest update works great in my Next.js app - thanks!

**Comment by mrspartak** [comment]
Hi @milesmcc, as I can tell you did not expose newHit function yet? Should I just use shynet.newPageLoad() for SPA then?

**Comment by milesmcc** [comment]
Yep! `Shynet.newPageLoad()` is what you want to use.

**Comment by mrspartak** [comment]
Thank you!
