### ISSUE TITLE
Document primary-key integration

### ISSUE THREAD

**Issue by mrspartak** [milesmcc/shynet#56]
Readme page says that I can associate visitors in Shynet with their user accounts on my site. But how? I can't find any clue to this.

**Comment by milesmcc** [comment]
You're right, I'm surprised this is not well documented. I'll leave this issue open until I add it to the docs.

In the meantime, here's how you do it: add the 'primary key' to the URL you load the tracking script from. So for example, if your Shynet script location (for either the pixel or the script) is `//shynet.example.com/ingress/your_service_uuid/pixel.gif` and `//shynet.example.com/ingress/your_service_uuid/script.js`, you'd add the primary key as an additional path between the service uuid and the resource, like so: ``//shynet.example.com/ingress/your_service_uuid/the_primary_key/pixel.gif` and ``//shynet.example.com/ingress/your_service_uuid/the_primary_key/script.js`.

**Comment by mrspartak** [comment]
I guess it would be much better to implement it also inside client API, because of SPA websites

**Comment by mrspartak** [comment]
Hi! But this is still not a solution for SPA. I guess using something like Shynet.PRIMARY_KEY = 2 on a client and then building an URL could solve this

**Comment by milesmcc** [comment]
It also works for SPAs, no? All you need to do is dynamically generate the script URL using JavaScript.

**Comment by mrspartak** [comment]
The user could be logged out, and when it logs in, I have no options to generate any links. Also, I never saw "analytics" front-end script, that asks to generate its link. All setup is done after it's loading via API.
We have apps that are getting current user information after loading. Also, they are entirely HTML without any backend rendering. That is one of the points of SPA after all.
I'm using Vue/Nuxt FYI.
