### ISSUE TITLE
Step by step guide with docker-compose

### ISSUE THREAD

**Issue by lucasrla** [milesmcc/shynet#58]
This is not an issue.

I just wanted to thank you all for Shynet and let you know that I have just published https://github.com/lucasrla/shynet-docker-lightsail

I took the basic instructions from the Usage Guide (i.e. HTTP-only install + Cloudflare as reverse proxy) and tweaked them to use docker-compose instead. I also added a few helper scripts to quicjly spin up a docker-ready Amazon Lightsail instance.

I hope it makes it even easier for newcomers to adopt Shynet.

Thanks again!

**Comment by milesmcc** [comment]
This is awesome! Thanks for putting this together. Feel free to submit a PR if you want to “upstream” some of these steps into the official Shynet guide.
