### ISSUE TITLE
uPlot (apex charts alternative)

### ISSUE THREAD

**Issue by leeoniya** [milesmcc/shynet#60]
hey @milesmcc

i came from https://news.ycombinator.com/item?id=23806037

allow me to shamelessly plug uPlot in case you were interested in evaluating alternatives to slow/bloated Apex: 

https://github.com/leeoniya/uPlot#performance

uPlot's origins are simular to this project (diy, minimal, analytics). you can read more of the story here: https://news.ycombinator.com/item?id=23045207

cheers!

**Comment by milesmcc** [comment]
Thanks for stopping by! I’d definitely be open to replacing ApexCharts, as it’s easily the most bloated part of Shynet. uPlot looks like a viable alternative, although it looks like I’d need to do a fair amount of styling to get it to work with Shynet’s visual identity.

That said, I don’t have any plans to do this in the short term, as Apex is working fine right now and there are higher priority items on the roadmap.

If you (or anyone else reading this) ever wants to do this in a PR, though, please go ahead!

**Comment by leeoniya** [comment]
sounds good, thanks!
