### ISSUE TITLE
Please add a requirements.txt

### ISSUE THREAD

**Issue by spapas** [milesmcc/shynet#61]
I presume you already have the requirements in a different format (Pipfile?) but could you just do a `pip freeze > requirements.txt` for us people that use good old pip?

**Comment by milesmcc** [comment]
Yes, we have a Pipfile in the repository root. If you'd like to use Pip, you'll unfortunately need to manually install the dependencies. Maintaining two different files for dependency management would add complexity that I'm not sure I want to handle.
