### ISSUE TITLE
Set hostname via env variable

### ISSUE THREAD

**Issue by b-m-f** [milesmcc/shynet#64]
What do you think of setting the hostname via an environment variable?

This way there is no need to set it by manually executing `./manage.py hostname`

**Comment by milesmcc** [comment]
It's challenging. The hostname isn't actually constant; it's actually just a layer on top of the [Django sites framework](https://docs.djangoproject.com/en/3.0/ref/contrib/sites/). Among other things, it's possible to have multiple hostnames and whitelabels for the same site, computed according which domain you're accessing.

Unless I'm mistaken, this is a convenience thing, so I'm not sure the complexity/convenience tradeoffs make this worthwhile?

**Comment by milesmcc** [comment]
This was originally how we did it, and it caused a lot of issues. Going to close this as a wontfix, unfortunately! Thanks for bringing it up nonetheless.
