### ISSUE TITLE
Fallback to <img> loading on XHR failure

### ISSUE THREAD

**Issue by VeryStrongFingers** [milesmcc/shynet#65]
Would it be worthwhile to attempt the loading of the fallback pixel image, in the case of XHR failure?
https://github.com/milesmcc/shynet/blob/213c44a45ae56e9344ceaa2ad6fc495822d08c07/shynet/analytics/templates/analytics/scripts/page.js#L23-L34

The pixel CORS header will always allow **any** host to connect
https://github.com/milesmcc/shynet/blob/510df192d8bdc989ac763896a4ce159fc4e109de/shynet/analytics/views/ingress.py#L89-L92

 so in the event of a CORS (or other) failure on XHR - falling back to loading the `<img src="..../pixel.gif">` would theoretically work.

I'm happy to do a PR for it, if deemed appropriate

**Comment by milesmcc** [comment]
Hmm. Thanks for pointing this out. You may have honestly found a bug — the CORS headers of the image shouldn’t be `*` always. Instead, they should match that of the script.

Hmm.

**Comment by VeryStrongFingers** [comment]
@milesmcc CORS doesn't apply to `<img>` tags according to https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#What_requests_use_CORS
Might not even need that header at all

**Comment by milesmcc** [comment]
Thanks for pointing out this issue. I realize the fix may have been the exact opposite of what you expected---origin checking is now enforced for images _too_---but that's ultimately a security consideration. I _thought_ that CORS was enforced for images, so when you pointed out that it wasn't, I realized that meant there was a way to get around origin enforcement!
