### ISSUE TITLE
Update JS heartbeat timer

### ISSUE THREAD

**Issue by VeryStrongFingers** [milesmcc/shynet#66]
The Shynet heartbeat function is currently invoked using `setInterval`
https://github.com/milesmcc/shynet/blob/213c44a45ae56e9344ceaa2ad6fc495822d08c07/shynet/analytics/templates/analytics/scripts/page.js#L40

This may cause issues in the event of the Shynet web server taking greater than configured heartbeat seconds to respond.

---

Example scenario:
- Your heartbeat is configured every 5 seconds
- Your web server is taking 8 seconds to respond, under load (or just being trash)

You will be end up sending more requests than the web server can handle and just make it worse. Essentially doing a mini DoS to your Shynet server.

--- 

We should update the heartbeat timer to use `setTimeout` and only start counting down **after** the XHR request has received a response.

Happy to do a PR for this one if it's a sound idea, although my JS isn't very polished

**Comment by haaavk** [comment]
Maybe skip a beat if there is no response on time and kill a beat if there is an error.
```javascript
var Shynet = {
  idempotency: null,
  heartbeatTaskId: null,
  skipHeartbeat: false,
  sendHeartbeat: function () {
    try {
      if (document.hidden) {
        return;
      }
      if (Shynet.skipHeartbeat) {
        console.warn("Heartbeat skipped due to lack of server response");
        return;
      }

      Shynet.skipHeartbeat = true;
      var xhr = new XMLHttpRequest();
      xhr.open(
        "POST",
        "{{protocol}}://{{request.site.domain|default:request.META.HTTP_HOST}}{{endpoint}}",
        true
      );
      xhr.setRequestHeader("Content-Type", "application/json");
      xhr.onload(function () {
        Shynet.skipHeartbeat = false;
      });
      xhr.send(
        JSON.stringify({
          idempotency: Shynet.idempotency,
          referrer: document.referrer,
          location: window.location.href,
          loadTime:
            window.performance.timing.domContentLoadedEventEnd -
            window.performance.timing.navigationStart,
        })
      );
    } catch (e) {
      clearInterval(Shynet.heartbeatTaskId);
      Shynet.heartbeatTaskId = null;
      console.error('Heartbeat killed due to an error');
    }
  },
  newPageLoad: function () {
    if (Shynet.heartbeatTaskId != null) {
      clearInterval(Shynet.heartbeatTaskId);
    }
    Shynet.idempotency = Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);
    Shynet.skipHeartbeat = false;
    Shynet.heartbeatTaskId = setInterval(Shynet.sendHeartbeat, parseInt("{{heartbeat_frequency}}"));
    Shynet.sendHeartbeat();
  }

```

**Comment by CasperVerswijvelt** [comment]
Would not kill the heartbeat interval when theres an error: if for some reason a heartbeat throws an error the rest of the session would no longer be recorded (Not sure what errors could happen here though since the request is sent asynchronously). I think nothing should stop the interval ever, we just need to not send a heartbeat when the previous heartbeat request hasn't finished yet.

Also set `Shynet.skipHeartbeat = false;` in the `xhr.onerror` handler so it does not keep skipping heartbeats indefinitely
