### ISSUE TITLE
Automatically remove Protocol from domain 

### ISSUE THREAD

**Issue by b-m-f** [milesmcc/shynet#68]
If setting the domain name with the protocol this will result in a broken tracking script.

F.E. setting the domain to `https://analytics.example.com` will use this to create the script 
```
<script src="https://https://analytics.example.com/ingress/3123/script.js">
```

To avoid this, some kind of validation should happen on the frontend, or the protocol should be stripped before saving it.

**Comment by milesmcc** [comment]
By domain name here, are we talking about what happens when you run `manage.py hostname <domain>`?

You're right that there should be some kind of validation.

**Comment by b-m-f** [comment]
Should be the hostname, yes.
It is the `sites.domain_name` relation on the admin dashboard
