### ISSUE TITLE
Fix the NPM_FILE_PATTERNS setting to work on windows

### ISSUE THREAD

**Issue by spapas** [milesmcc/shynet#69]
Instead of hardcoding the "/" to the entries `NPM_FILE_PATTERNS` you need to use `os.path.join`, as per: https://github.com/kevin1024/django-npm/issues/15

For example:

```
NPM_FILE_PATTERNS = {
    "a17t": [os.path.join("dist", "a17t.css"), os.path.join("dist", "tailwind.css")],
    "apexcharts": [os.path.join("dist", "apexcharts.min.js")],
    "litepicker": [os.path.join("dist", "js", "main.js")],
    "turbolinks": [os.path.join("dist", "turbolinks.js")],
    "stimulus": [os.path.join("dist", "stimulus.umd.js")],
    "inter-ui": [os.path.join("Inter (web)", "*")],
    "@fortawesome": [os.path.join("fontawesome-free", "js", "all.min.js")],
}
```

TIA

**Comment by milesmcc** [comment]
You’re right, this is definitely something we should do. If you’d like, feel free to submit a PR! Seems like you’ve already done most of the work in your comment. Or I can implement this myself if that’s not something you’re interested in.

**Comment by spapas** [comment]
Hello @milesmcc, I can't provide a PR right now - I'm at a different computer so I recommend fixing it yourself.

Kind regards,
Serafeim
