### ISSUE TITLE
Using docker-compose doesn't bind port on the host

### ISSUE THREAD

**Issue by MagnumDingusEdu** [milesmcc/shynet#70]
If you're using docker-compose to deploy the service, the service isn't accessible at all on the host machine. 

Instead of 
```docker
    expose:
      - 8080
```

it should be 
```
    ports:
      - 127.0.0.1:8080:8080
```

The `expose` would work just fine if there was a webserver (like caddy/nginx) included in the docker-compose file. 
Also, there isn't a section for how to deploy using docker-compose in `GUIDE.md`, which is a much easier way to get this up and running. I'd like to work on that, if it's okay.

**Comment by milesmcc** [comment]
Hey! Thanks for this bug report. Feel free to submit a PR to fix this! I don't have much experience with docker-compose (I'm not the original author of that deployment option), so feel free to tackle this yourself.
