### ISSUE TITLE
Sites displayed multiple times when adding collaborators

### ISSUE THREAD

**Issue by pehbehbeh** [milesmcc/shynet#78]
The page is displayed multiple times when adding collaborators. It is displayed 2 times in total when adding 2 collaborators and 4 times in total when adding 4 collaborators.

<img width="1064" alt="Privacy-oriented_analytics___Shynet" src="https://user-images.githubusercontent.com/133831/91525196-3d3f0200-e901-11ea-8d4f-88a61326b555.png">

**Comment by milesmcc** [comment]
Whoah, that’s... definitely something. Did you add yourself as a collaborator? Are all the collaborators different email addresses?

I haven’t been able to replicate this, but it’s clearly a bug. Which version of Shynet are you running?

**Comment by pehbehbeh** [comment]
I am running version 0.6.2 and all different email addresses.

I am not familiar with Django... maybe I got something wrong. I added users via the Django administration `/admin/core/user/`, attached the email addresses `/admin/account/emailaddress/` and then added the collaborators via Shynet administration (site -> manage).

**Comment by milesmcc** [comment]
Ok, I will fix this bug shortly. I'm sorry if this is frustrating for you, but could you confirm that the email addresses listed as collaborators are linked to separate core user accounts? I'm just curious as to how this bug came about.

**Comment by milesmcc** [comment]
Fixed in v0.6.5! Feel free to reopen the issue if the update doesn't solve your problem.

**Comment by pehbehbeh** [comment]
It is fixed now. Thanks!
