### ISSUE TITLE
Username instead of email

### ISSUE THREAD

**Issue by AliMickey** [milesmcc/shynet#79]
Request to enable username login instead of email.

**Comment by milesmcc** [comment]
Sorry, unfortunately this would require some significant reworking of the collaboration workflow, and email authentication is starting to become de-facto across the web, so this isn't something I think we'll be able to do.

**Comment by milesmcc** [comment]
Thanks for the issue, though!

**Comment by AliMickey** [comment]
Would an alias just for login be possible then?

**Comment by milesmcc** [comment]
It’s possible to add multiple emails to your account, but they still need to be in the form of an email address.

**Comment by AliMickey** [comment]
I meant like keep emails as the main authentication for the project, but have say "User1" = "user@domain.com" be a valid login but only for login nothing else.

**Comment by milesmcc** [comment]
I understand—I guess what I’m saying is that with our current auth system, this isn’t possible.
