### ISSUE TITLE
Embed tracking pixel in css instead of html

### ISSUE THREAD

**Issue by mansguiche** [milesmcc/shynet#84]
I am running a web service via a docker container. Since I am not the developer of this docker container I can not modify the code easily. The web service does have administrator settings for adding custom css, however. I thought that this would be enough to embed the 1x1 pixel using `body:after{content:url(<pixel_url>);}` and that shynet would be able to use the data from that but unforunately I am seeing no data on shynet from it. The pixel is definitely loaded on all the pages of the web service.

Is this possible or have I completely misunderstood how the pixel tracking works?

**Comment by mansguiche** [comment]
Appologies, It does seem to work. My browser was sending a do not track header. Once I turned it off it worked fine.

**Comment by milesmcc** [comment]
I'm glad you found the issue! This is a very creative way of running Shynet...! :)
