### ISSUE TITLE
How to run locally?

### ISSUE THREAD

**Issue by mooseyoose** [milesmcc/shynet#88]
How do I run this locally? What IP do I use? I tried setting the ip to local host but I can't access it.

Thanks.

**Comment by soneji** [comment]
if you download the `docker-compose.yml` file from [here](https://github.com/milesmcc/shynet/blob/master/docker-compose.yml) and run 
`docker-compose up` in the directory you saved the file
it should start the server on `http://localhost:8080`

**Comment by milesmcc** [comment]
Thanks @soneji.
