### ISSUE TITLE
Deploy as a service on Debian/Ubuntu

### ISSUE THREAD

**Issue by morey-tech** [milesmcc/shynet#9]
This project looks really great and I'm interested in running it for my personal websites. I'm wondering if Shynet can be deployed as a service on a Debian/Ubuntu instance (e.g. using LXC) instead of using Docker. Do you have any plans to add documentation for this?

**Comment by milesmcc** [comment]
I think this would be a great addition. This isn't the way I typically deploy Shynet and I don't have any real experience with deploying services on Debian, though, so I don't think I'm in a position to write this documentation myself.

If anyone else is able to write this up, I'll happily include it!

**Comment by spapas** [comment]
Continuing on this could you provide a rough guide on how to deploy shynet *without* docker? Beyond Django/gunicorn what other things does this project require? I presume celery, but which broker it uses?

Also is there a concept of releases or I'll need to just clone master from GitHub? 

Docker for deploying in production is a no-no for me (and for many others) so providing some starting point would be appreciated very much!

**Comment by milesmcc** [comment]
Closing because the getting started guide has evolved quite a bit from here. (And there's nothing wrong with deploying using docker-compose, if you prefer a single-instance setup.)

**Comment by CarlSinclair** [comment]
I'm glad this has already been asked. I run RHEL, but it's the same idea. I'd like to install it directly without relying on docker (bloat) or any external services (cost).

**Comment by milesmcc** [comment]
I'd welcome a PR that provides guidance on how to run Shynet as a service! It isn't something I've done myself so I'm unfortunately not in a position to write up good documentation on it, but I imagine running Shynet would be similar to running any other kind of service.

**Comment by CarlSinclair** [comment]
I just tried to go the docker route and it did not work at all. The step involving ./manage.py to create the user account failed with errors. Sadly I don't have any more time to dedicate to it at the moment.
