### ISSUE TITLE
GeoIP Map

### ISSUE THREAD

**Issue by agucova** [milesmcc/shynet#92]
While the current "Country" table is fine for most purposes, I feel that a more visual representation is useful to catch geographical trends (by example, continents) and easier to interpret.

I propose adding a simple map colored according to the number of sessions in each country. This could be enabled directly from the table (as a toggle), or maybe from settings.

It would be necessary to bundle a vector map (I doubt using an external map API is a good idea), for which something like [DataMaps](https://datamaps.github.io/) could be used (global map is 32KB gzipped).

**Comment by milesmcc** [comment]
This would be awesome, but I'm not sure I have the bandwidth to work on this at the moment. Please feel free to open a PR if you can implement this!

**Comment by CasperVerswijvelt** [comment]
Started working on this and got this functional now:
![image](https://user-images.githubusercontent.com/25928551/115792432-94cb3a00-a3ca-11eb-9942-4de2904c0da1.png)

Still work in progress, let me know what you think

**Comment by milesmcc** [comment]
Looking great @CasperVerswijvelt! One thing: we might want to find some way to encapsulate & add a top label to the map. But I'm excited to see where this goes!

**Comment by CasperVerswijvelt** [comment]
Added a header and cleaned up my code a bit.

My concerns right now:

- Placement: I think it's too prominent in the desktop layout taking up 2 colums but 1 column might be a little too small to conveniently use (and it will leave a column of white space). 
  - Maybe this card should get a page for itself? 
  - Maybe we should be able to toggle between country data as a table and as a map chart (like @agucova 's original idea) but where do I place the toggle button for this?
- In the default world map of the [Datamaps library ](https://datamaps.github.io/) Russia is split, we should avoid this so we can have consistent padding all around the card but I have not found how to do this yet

let me know what you guys think
| Phone | Desktop |
|-------|---------|
| ![analytics casperverswijvelt be_dashboard_service_ba385d2a-5c80-4b31-931e-3da309fac8d0__startDate=2021-4-22 endDate=2021-4-24(iPhone X)](https://user-images.githubusercontent.com/25928551/115937985-89930f80-a499-11eb-8d04-48fdb6a826bb.png)  |   ![image](https://user-images.githubusercontent.com/25928551/115937983-8861e280-a499-11eb-8b62-6ec7948a4b37.png) |
