### ISSUE TITLE
Multiple hosts using same instance

### ISSUE THREAD

**Issue by wvffle** [milesmcc/shynet#98]
So, I have a server with a few services that I share with my friends. All of us have our own domains and basically we want to have the same instance linked under different hostnames.

In the .env file, we can set `ALLOWED_HOSTS` to the allowed hostnames though we still need to set up one hostname that will be used in all of our scripts. In my opinion this single hostname is unneeded, as you can generate the tracking scripts based on the origin of dashboard the current user is using. 

The drawback of current approach is that, when you want to track 2 or more different websites, both websites will make requests to the same hostname, that means you can identify that all of them probably belong to the same person/entity. 

Generating scripts based of the hostname of dashboard deals with that problem.

**Comment by JuniorJPDJ** [comment]
Yop, why not just use hostname of accessed panel? When I open shynet from `example.org` show script with `example.org` url, when accessed from `example.net` use `example.net`.

**Comment by milesmcc** [comment]
This makes sense. Feel free to open a PR and I'll gladly accept.
